### ISSUE TITLE
openssl_platform_init.c: ASSERT raising error when resolving static linked libcrypto with musl

### ISSUE THREAD

**Issue by BestITUserEUW** [awslabs/aws-c-cal#110]
Hey,
i'm trying to integrate the aws-iot-sdk-cpp-sdk-v2 into my project. I'm running on arm64 and compiling with musl. Compilation works fine but when trying to start the executable is Raises this Assert Error from openssl_platform_init.c:
      l. 488    `AWS_FATAL_ASSERT(process && "Unable to load symbols from process space");`
When i'm not using the musl toolchain it works fine. There are other people encountering the same issue as me. See here https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/308.  Is there a way to fix this?
Full Error Output:
`Fatal error condition occurred in /pathTo/openssl_platform_init.c:488: process && "Unable to load symbols from process space"
Exiting Application
No call stack information available
qemu: uncaught target signal 6 (Aborted) - core dumped
Aborted (core dumped)
`

**Comment by jmklix** [comment]
The sdk that you linked does not currently support alpine linux. The issue that you linked has been converted to an feature request. Closing this issue for now, but please reopen if you are still seeing this issue after alpine support is added.
