### ISSUE TITLE
versioning policy

### ISSUE THREAD

**Issue by thomas-roos** [awslabs/aws-c-cal#117]
Hi, I'm working on https://github.com/aws4embeddedlinux/meta-aws and wonder if you do have a versioning policy such as:
https://github.com/aws/s2n-tls/blob/main/VERSIONING.rst
Best, 
Thomas

**Comment by jmklix** [comment]
Yes, we follow that versioning policy. We are currently on version 0.7.0. We still might might breaking changes in the future
