### ISSUE TITLE
Test binaries installed in bin/

### ISSUE THREAD

**Issue by stewartsmith** [awslabs/aws-c-cal#119]
This snippet of Cmake

```
if (NOT CMAKE_CROSSCOMPILING AND NOT BYO_CRYPTO)
    include(CTest)
    if (BUILD_TESTING)
        add_subdirectory(bin/sha256_profile)
        add_subdirectory(bin/produce_x_platform_fuzz_corpus)
        add_subdirectory(bin/run_x_platform_fuzz_corpus)
        add_subdirectory(tests)
    endif()
endif()
```

and the recursive CMake results in these binaries being installed in bin/, but these appear to be project internal test programs? When packaged for a Linux distribution such as Fedora or Amazon Linux, do you intend to have these binaries land in `/usr/bin` for customers to use?

**Comment by TingDaoK** [comment]
resolved with https://github.com/awslabs/aws-c-cal/pull/177
