### ISSUE TITLE
‘CRYPTO_LOCK’ undeclared when compiling with custom openssl and libcurl

### ISSUE THREAD

**Issue by sathishk-r** [awslabs/aws-c-cal#122]
Hi,
I am trying to build aws kinsesis c++ sdk in ubuntu 18.04.6 with custom openssl and libcurl. in my case our openssl is a customised version of 1.1.1n and it is built without deprecated api's (i.e no CRYPTO_LOCK defined).

```
 aws-sdk-cpp-1.9.318/crt/aws-crt-cpp/crt/aws-c-cal/source/unix/openssl_platform_init.c:524:16: error: ‘CRYPTO_LOCK’ undeclared (first use in this function); did you mean ‘CRYPTO_RWLOCK’?
 if (mode & CRYPTO_LOCK)
            ^~~~~~~~~~~
            CRYPTO_RWLOCK
```

 is there a way to fix this ?

**Comment by jmklix** [comment]
Can you see if you still get this error when pointing to other versions of openssl? There are some old versions where they tried to remove 'CRYPTO_LOCK' and that might be what your customized version is based on
