### ISSUE TITLE
OpenSSL >= 3.0.0 support

### ISSUE THREAD

**Issue by jmklix** [awslabs/aws-c-cal#132]
Transferred from [aws-iot-device-sdk-cpp-v2](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/499)

### Describe the feature

This transition has to be done eventually anyway.

### Use Case

I'm developing an application which uses OpenSSL 3.0.,x but this started to crash due to segmentation faults a while back.
I tracked the issue and I think the bug is caused by libcurl and AWS SDK using different OpenSSL versions.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

v1.19.1, v1.19.3

### Environment details (OS name and version, etc.)

Manjaro Linux 22.0.0

**Comment by jmklix** [comment]
This is something that we are currently working on, but I don't have any detailed for when it will be released

**Comment by jmklix** [comment]
P78204515

**Comment by graebm** [comment]
aws-c-cal does seem to support using libcrypto from OpenSSL 3. I re-opened the ticket in the IoT SDK. The real issue seems to be a user application where two different versions of libcrypto were being used at the same time. The solution is probably to only have 1 libcrypto in use by the application
