### ISSUE TITLE
`EVP_PKEY*`  APIs vs `EC_KEY*` APIs

### ISSUE THREAD

**Issue by justinboswell** [awslabs/aws-c-cal#27]
Q: OpenSSL states that their long term support would be for the more general `EVP_PKEY*`  apis and not the low level `EC_KEY*`  apis ones. The EC_KEY apis are opaque in the newer long term supported version. Given this, do we want to use the more generic `EVP_PKEY *`?

_Originally posted by @ttjsu-aws in https://github.com/awslabs/aws-c-cal/pull/23_

**Comment by bretambrose** [comment]
Is this still an open question or can I make it disappear?

**Comment by yasminetalby** [comment]
Hello @justinboswell ,

I am closing this issue as there was no engagement for over 2 years. If you have any further question or need for support you can open a new issue within our repository.

Thank you very much for your time and collaboration.

Sincerely,

Yasmine
